#!/usr/bin/expect -f

# 自动调整终端大小
trap {
    set rows [stty rows]
    set cols [stty columns]
    stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

# ---------- 参数 ----------
set node_ip  [lindex $argv 0]
set cpe_ip   [lindex $argv 1]
set username [lindex $argv 2]
set password [lindex $argv 3]
set mode     [lindex $argv 4]

# ---------- 密码 ----------
set O_PWD OnM
set X_PWD XnM
set timeout 5

# SSH 登录
proc ssh_login {user host port passwd} {
    spawn ssh -o StrictHostKeyChecking=no $user@$host -p $port
    expect {
        "yes/no" {
            send "yes\r"
            expect "*assword:" { send "$passwd\r" }
        }
        "*assword:" { send "$passwd\r" }
        timeout { send_error "User $user login timeout.\n"; exit 1 }
    }
}

# 切换 root
proc switch_root {passwd} {
    send "su -\r"
    expect "*assword:"
    send "$passwd\r"
    expect "#"
}

# SSH 到 CPE
proc ssh_cpe {cpe_ip user mode o_pwd x_pwd} {
    send "ssh -i /etc/openvpn/server/box $user@$cpe_ip -p 7722\r"
    expect {
        "yes/no" { send "yes\r"; expect "Enter passphrase for key '/etc/openvpn/server/box':" { send "$o_pwd\r" } }
        "Enter passphrase for key '/etc/openvpn/server/box':" { send "$o_pwd\r" }
        timeout { send_error "ssh $cpe_ip login timeout.\n"; exit 1 }
    }

    # 如果是普通模式，切换 root
    if {$mode != "ucpe"} {
        expect "$"
        switch_root $x_pwd
    }
    expect "#"
    send "7xcli_info|head -n 1\r"
    interact
}

# 登录跳板机
ssh_login $username master.jump.7x-networks.net 2222 $password

expect "Opt>"
send "$node_ip\r"
expect "seven@*~]$"

# 切换 root
switch_root $X_PWD

# SSH 到目标 CPE
if {$mode != "ucpe"} {
    ssh_cpe $cpe_ip "seven" $mode $O_PWD $X_PWD
} else {
    ssh_cpe $cpe_ip "root" $mode $O_PWD $X_PWD
}
